services:
  mongo:
    image: mongo:6
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--bind_ip_all"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-container
    restart: always
    ports:
      - "5005:5005"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mern_db

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3005:80"  # Serve React on http://localhost:3000
    depends_on:
      - backend

volumes:
  mongo_data:

